## useful source: https://www.fredasongdrechsler.com/data-crunching/connect-wrds

In [1]:
import wrds

In [4]:
conn=wrds.Connection()

Enter your WRDS username [yjaey]: yjaeyoon
Enter your password: ···············

WRDS recommends setting up a .pgpass file.

Create .pgpass file now [y/n]?:  y

Created .pgpass file successfully.
Loading library list...
Done

In [16]:
conn.list_libraries()

['aha',
 'aha_sample',
 'ahasamp',
 'audit',
 'audit_acct_os',
 'audit_audit_comp',
 'audit_common',
 'audit_corp_legal',
 'auditsmp',
 'auditsmp_all',
 'bank',
 'blab',
 'block',
 'block_all',
 'boardex',
 'boardex_eur',
 'boardex_na',
 'boardex_row',
 'boardex_trial',
 'boardex_uk',
 'boardsmp',
 'bvd',
 'bvd_ama_large',
 'bvd_ama_medium',
 'bvd_ama_small',
 'bvd_ama_verylarge',
 'bvdsamp',
 'calcbench_trial',
 'calcbnch',
 'cboe',
 'cboe_all',
 'centris',
 'ciq',
 'ciq_capstrct',
 'ciq_common',
 'ciq_pplintel',
 'ciq_transactions',
 'ciqsamp',
 'ciqsamp_common',
 'ciqsamp_transcripts',
 'cisdm',
 'cisdmsmp',
 'comp',
 'comp_bank',
 'comp_bank_daily',
 'comp_execucomp',
 'comp_global',
 'comp_global_daily',
 'comp_na_annual_all',
 'comp_na_daily_all',
 'comp_na_monthly_all',
 'comp_segments_hist',
 'comp_segments_hist_daily',
 'comp_snapshot',
 'compa',
 'compb',
 'compbd',
 'compdcur',
 'compg',
 'compgd',
 'comph',
 'compm',
 'compmcur',
 'compnad',
 'compsamp',
 'compsamp_snapshot',
 'compseg',
 'compsegd',
 'compsnap',
 'comscore',
 'contrib',
 'contrib_ceo_turnover',
 'contrib_char_returns',
 'contrib_general',
 'contrib_intangible_value',
 'contrib_kpss',
 'contrib_liva',
 'crsp',
 'crsp_a_ccm',
 'crsp_a_indexes',
 'crsp_a_stock',
 'crsp_a_treasuries',
 'crsp_a_ziman',
 'crsp_q_indexhist',
 'crsp_q_mutualfunds',
 'crspa',
 'crspm',
 'crspq',
 'crspsamp',
 'csmar',
 'csmar_af',
 'csmar_cd',
 'csmar_cg',
 'csmar_colc',
 'csmar_financial',
 'csmar_funds',
 'csmar_hld',
 'csmar_ini',
 'csmar_ipo_a',
 'csmar_ma',
 'csmar_rs',
 'csmar_trade',
 'dealscan',
 'djones',
 'djones_all',
 'dmef',
 'dmef_all',
 'doe',
 'doe_all',
 'emdb',
 'etfg',
 'etfg_samp',
 'etfgsamp',
 'eureka',
 'eurekahedge_sample',
 'eursamp',
 'evts',
 'execcomp',
 'factsamp_all',
 'factsamp_revere',
 'factset',
 'ff',
 'ff_all',
 'fisd',
 'fisd_common',
 'fisd_fisd',
 'fisd_naic',
 'fisdsamp',
 'fisdsamp_all',
 'fjc',
 'fjc_linking',
 'fjc_litigation',
 'frb',
 'frb_all',
 'fssamp',
 'ftse',
 'ftsesamp',
 'ginsight',
 'gmi',
 'govpx',
 'govpxsmp',
 'gsi',
 'gsidemo_all',
 'hbase',
 'hbase_sample',
 'hbsamp',
 'hfr',
 'hfrsamp',
 'hfrsamp_hfrdb',
 'ibes',
 'ibescorp',
 'ibeskpi',
 'ifgr',
 'ifgrsamp',
 'ims',
 'ims_obp_trial',
 'imssamp',
 'infogroupsamp_business',
 'infogroupsamp_residential',
 'iri',
 'iss',
 'iss_incentive_lab',
 'iss_incentive_lab_europe',
 'iss_va_shareholder',
 'issm',
 'kld',
 'kld_histall',
 'ktmine',
 'ktmine_patents_samp',
 'ktsamp',
 'levin',
 'lspd',
 'lspdsamp',
 'lvnsamp',
 'lvnsamp_all',
 'macrofin',
 'macrofin_comm_trade',
 'markit',
 'mfl',
 'mflinks_all',
 'midas',
 'mrktsamp',
 'mrktsamp_cds',
 'mrktsamp_cdx',
 'mrktsamp_msf',
 'msfanly',
 'msfinst',
 'msrb',
 'msrb_all',
 'msrbsamp',
 'nastraq',
 'omtrial',
 'optionm',
 'optionm_all',
 'optionmsamp_europe',
 'optionmsamp_us',
 'otc',
 'otc_endofday',
 'pacap',
 'phlx',
 'phlx_all',
 'pitchbk',
 'pitchsmp',
 'ppublica',
 'ppubsamp',
 'ppubsamp_d4d',
 'preqin',
 'preqsamp',
 'preqsamp_all',
 'public',
 'public_all',
 'pwt',
 'pwt_all',
 'ravenpack_trial',
 'rent',
 'reprisk',
 'reprisk_sample',
 'repsamp',
 'revere',
 'risk',
 'risk_directors',
 'risk_governance',
 'risksamp',
 'risksamp_all',
 'rpa',
 'rpna',
 'rpnasamp',
 'rq_all',
 'sdc',
 'sdcsamp',
 'secsamp',
 'secsamp_all',
 'snapsamp',
 'snl',
 'snlsamp',
 'snlsamp_fig',
 'sprat',
 'sustain',
 'sustainalyticssamp_all',
 'sustsamp',
 'taq',
 'taqm_2014',
 'taqm_2015',
 'taqm_2016',
 'taqm_2017',
 'taqm_2018',
 'taqm_2019',
 'taqmsamp',
 'taqmsec',
 'taqsamp',
 'tass',
 'tfn',
 'totalq',
 'totalq_all',
 'toyo',
 'toyosamp',
 'toyosamp_all',
 'tr_13f',
 'tr_dealscan',
 'tr_ds',
 'tr_ibes',
 'tr_ibes_guidance',
 'tr_insiders',
 'tr_mutualfunds',
 'tr_tass',
 'trace',
 'trace_enhanced',
 'trace_standard',
 'trdssamp',
 'trdstrm',
 'tresg',
 'trown',
 'trsamp',
 'trsamp_ds_eq',
 'trsamp_dscom',
 'trsamp_dsecon',
 'trsamp_dsfut',
 'trsamp_sdc_ma',
 'trsamp_sdc_ni',
 'trsamp_worldscope',
 'trsdcgs',
 'trucost',
 'trws',
 'twoiq',
 'twoiq_samp',
 'twoiqsmp',
 'wappsamp',
 'wcai',
 'wind',
 'windsmp',
 'wqa',
 'wrds_lib_internal',
 'wrdsapps',
 'wrdsapps_backtest_basic',
 'wrdsapps_backtest_plus',
 'wrdsapps_bondret',
 'wrdsapps_eushort',
 'wrdsapps_evtstudy_int_ginsight',
 'wrdsapps_evtstudy_lr',
 'wrdsapps_finratio',
 'wrdsapps_finratio_ccm',
 'wrdsapps_finratio_ibes',
 'wrdsapps_finratio_ibes_ccm',
 'wrdsapps_link_comp_eushort',
 'wrdsapps_link_crsp_bond',
 'wrdsapps_link_crsp_comp_bdx',
 'wrdsapps_link_crsp_factset',
 'wrdsapps_link_crsp_ibes',
 'wrdsapps_link_crsp_optionm',
 'wrdsapps_link_datastream_wscope',
 'wrdsapps_link_supplychain',
 'wrdsapps_patents',
 'wrdsapps_subsidiary',
 'wrdsapps_windices',
 'wrdsappssamp_all',
 'wrdsrpts',
 'wrdsrpts_rep_usage',
 'wrdssec',
 'wrdssec_all',
 'wrdssec_bow',
 'wrdssec_common',
 'wrdssec_insiders',
 'wrdssec_midas',
 'wrdssec_secsa',
 'zacks',
 'zacksamp',
 'zacksamp_all']

In [17]:
conn.list_tables(library="comp")

['aco_amda',
 'aco_imda',
 'aco_indfnta',
 'aco_indfntq',
 'aco_indfntytd',
 'aco_indsta',
 'aco_indstq',
 'aco_indstytd',
 'aco_notesa',
 'aco_notesq',
 'aco_notessa',
 'aco_notesytd',
 'aco_pnfnda',
 'aco_pnfndq',
 'aco_pnfndytd',
 'aco_pnfnta',
 'aco_pnfntq',
 'aco_pnfntytd',
 'aco_transa',
 'aco_transq',
 'aco_transsa',
 'aco_transytd',
 'adsprate',
 'asec_amda',
 'asec_imda',
 'asec_notesa',
 'asec_notesq',
 'asec_transa',
 'asec_transq',
 'bank_aacctchg',
 'bank_adesind',
 'bank_afnd1',
 'bank_afnd2',
 'bank_afnddc1',
 'bank_afnddc2',
 'bank_afntind',
 'bank_funda',
 'bank_funda_fncd',
 'bank_fundq',
 'bank_fundq_fncd',
 'bank_iacctchg',
 'bank_idesind',
 'bank_ifndq',
 'bank_ifndytd',
 'bank_ifntq',
 'bank_ifntytd',
 'bank_names',
 'bank_namesq',
 'chars',
 'co_aacctchg',
 'co_aaudit',
 'co_adesind',
 'co_adjfact',
 'co_afnd1',
 'co_afnd2',
 'co_afnddc1',
 'co_afnddc2',
 'co_afntind1',
 'co_afntind2',
 'co_ainvval',
 'co_amkt',
 'co_busdescl',
 'co_cotype',
 'co_filedate',
 'co_fortune',
 'co_hgic',
 'co_iacctchg',
 'co_iaudit',
 'co_idesind',
 'co_ifndq',
 'co_ifndsa',
 'co_ifndytd',
 'co_ifntq',
 'co_ifntsa',
 'co_ifntytd',
 'co_imkt',
 'co_industry',
 'co_ipcd',
 'co_mthly',
 'co_offtitl',
 'company',
 'currency',
 'dd_group',
 'dd_group_xref',
 'dd_item',
 'dd_package',
 'ecind_desc',
 'ecind_mth',
 'exrt_dly',
 'exrt_mth',
 'filings',
 'funda',
 'funda_fncd',
 'fundq',
 'fundq_fncd',
 'g_chars',
 'g_co_aaudit',
 'g_co_adesind',
 'g_co_afnd1',
 'g_co_afnd2',
 'g_co_afnddc1',
 'g_co_afnddc2',
 'g_co_afntind1',
 'g_co_afntind2',
 'g_co_ainvval',
 'g_co_hgic',
 'g_co_iaudit',
 'g_co_idesind',
 'g_co_ifndq',
 'g_co_ifndsa',
 'g_co_ifndytd',
 'g_co_ifntq',
 'g_co_ifntsa',
 'g_co_ifntytd',
 'g_co_industry',
 'g_co_ipcd',
 'g_co_offtitl',
 'g_company',
 'g_currency',
 'g_ecind_desc',
 'g_ecind_mth',
 'g_exrt_dly',
 'g_exrt_mth',
 'g_funda',
 'g_funda_fncd',
 'g_fundq',
 'g_fundq_fncd',
 'g_idx_daily',
 'g_idx_index',
 'g_idx_mth',
 'g_idxcst_his',
 'g_names',
 'g_names_ix',
 'g_names_ix_cst',
 'g_namesq',
 'g_sec_adesind',
 'g_sec_adjfact',
 'g_sec_afnd',
 'g_sec_afnddc',
 'g_sec_afnt',
 'g_sec_divid',
 'g_sec_dprc',
 'g_sec_dtrt',
 'g_sec_history',
 'g_sec_idesind',
 'g_sec_ifnd',
 'g_sec_ifnt',
 'g_sec_split',
 'g_secd',
 'g_secnamesd',
 'g_security',
 'g_sedolgvkey',
 'g_tmptable_pkg6153_tbl4023',
 'idx_ann',
 'idx_anndes',
 'idx_daily',
 'idx_index',
 'idx_mth',
 'idx_qrt',
 'idx_qrtdes',
 'idxcst_his',
 'io_qaggregate',
 'io_qbuysell',
 'io_qchanges',
 'io_qfloatadj',
 'io_qholders',
 'it_mbuysell',
 'it_msummary',
 'it_r_rltn',
 'names',
 'names_aco_indsta',
 'names_aco_indstq',
 'names_aco_pnfnda',
 'names_aco_pnfndq',
 'names_adsprate',
 'names_ix',
 'names_ix_cst',
 'names_seg',
 'namesd',
 'namesm',
 'namesq',
 'r_accstd',
 'r_acqmeth',
 'r_auditors',
 'r_auopic',
 'r_balpres',
 'r_cf_formt',
 'r_co_status',
 'r_coindpre',
 'r_compstat',
 'r_consol',
 'r_country',
 'r_cstclscd',
 'r_datacode',
 'r_datafmt',
 'r_divtaxmarker',
 'r_docsrce',
 'r_ex_codes',
 'r_exchgtier',
 'r_exrt_typ',
 'r_fndfntcd',
 'r_footnts',
 'r_foricd',
 'r_giccd',
 'r_hcalendr',
 'r_idxclscd',
 'r_inactvcd',
 'r_incstats',
 'r_indfmt',
 'r_indsec',
 'r_invval',
 'r_issuetyp',
 'r_majidxcl',
 'r_mic_codes',
 'r_naiccd',
 'r_notetype',
 'r_ntsubtype',
 'r_offcrso',
 'r_ogmethod',
 'r_opinions',
 'r_prc_stat',
 'r_qsrcdoc',
 'r_sec_stat',
 'r_secannfn',
 'r_sectors',
 'r_siccd',
 'r_spiicd',
 'r_spmicd',
 'r_statalrt',
 'r_states',
 'r_stko',
 'r_titles',
 'r_updates',
 'sec_adesind',
 'sec_adjfact',
 'sec_afnd',
 'sec_afnddc',
 'sec_afnt',
 'sec_divid',
 'sec_dprc',
 'sec_dtrt',
 'sec_history',
 'sec_idesind',
 'sec_ifnd',
 'sec_ifnt',
 'sec_mdivfn',
 'sec_mshare',
 'sec_msptfn',
 'sec_mth',
 'sec_mthdiv',
 'sec_mthprc',
 'sec_mthspt',
 'sec_mthtrt',
 'sec_shortint',
 'sec_spind',
 'sec_split',
 'secd',
 'secm',
 'security',
 'sedolgvkey',
 'seg_ann',
 'seg_annfund',
 'seg_customer',
 'seg_geo',
 'seg_naics',
 'seg_product',
 'seg_type',
 'spidx_cst',
 'spind',
 'spind_dly',
 'spind_mth',
 'tmptable_pkg6153_tbl4023',
 'wrds_seg_customer',
 'wrds_seg_geo',
 'wrds_seg_product',
 'wrds_segmerged',
 'xfl_column',
 'xfl_table']

In [24]:
company=conn.get_table(library='comp', table='company', obs=5)
print(company.shape)
company.head()

(5, 39)

,conm,gvkey,add1,add2,add3,add4,addzip,busdesc,cik,city,...,priusa,sic,spcindcd,spcseccd,spcsrc,state,stko,weburl,dldte,ipodate
0,A & E PLASTIK PAK INC,001000,None,None,None,None,None,None,None,None,...,01,3089,325.0,978.0,None,None,0.0,None,1978-06-30,None
1,A & M FOOD SERVICES INC,001001,1924 South Utica Avenue,None,None,None,94104,None,0000723576,Tulsa,...,01,5812,420.0,978.0,None,OK,0.0,None,1986-07-31,None
2,AAI CORP,001002,124 Industry Lane,None,None,None,21030-0126,"AAI Corporation, together with its subsidiarie...",0000001745,Hunt Valley,...,01,3825,230.0,940.0,None,MD,0.0,None,1977-03-31,None
3,A.A. IMPORTING CO INC,001003,7700 Hall Street,None,None,None,63125,"A.A. Importing Company, Inc. designs, manufact...",0000730052,St. Louis,...,01,5712,449.0,976.0,None,MO,3.0,www.aaimporting.com,1992-04-30,None
4,AAR CORP,001004,"One AAR Place, 1100 North Wood Dale Road",None,None,None,60191,AAR Corp. provides products and services to co...,0000001750,Wood Dale,...,01,5080,110.0,925.0,B,IL,0.0,www.aarcorp.com,None,1988-01-01

In [25]:
company=conn.get_table(library='comp', table='company', 
                    columns = ['conm', 'gvkey', 'cik'], obs=5)
print(company.shape)
company.head()

(5, 3)

                      conm   gvkey         cik
0    A & E PLASTIK PAK INC  001000        None
1  A & M FOOD SERVICES INC  001001  0000723576
2                 AAI CORP  001002  0000001745
3    A.A. IMPORTING CO INC  001003  0000730052
4                 AAR CORP  001004  0000001750

In [30]:
apple= conn.raw_sql("""select permno, date, prc, ret, shrout 
                    from crsp.msf
                    where permno= 14593 and date >= '01/01/2020'""",
                  date_cols=['date'])
apple

     permno       date         prc       ret      shrout
0   14593.0 2020-01-31  309.510010  0.054010   4375480.0
1   14593.0 2020-02-28  273.359985 -0.114310   4375480.0
2   14593.0 2020-03-31  254.289993 -0.069761   4323987.0
3   14593.0 2020-04-30  293.799988  0.155374   4334335.0
4   14593.0 2020-05-29  317.940002  0.084956   4334335.0
5   14593.0 2020-06-30  364.799988  0.147386   4283939.0
6   14593.0 2020-07-31  425.040009  0.165132   4275634.0
7   14593.0 2020-08-31  129.039993  0.216309  17102536.0
8   14593.0 2020-09-30  115.809998 -0.102526  16976763.0
9   14593.0 2020-10-30  108.860001 -0.060012  17001802.0
10  14593.0 2020-11-30  119.050003  0.095490  17001802.0
11  14593.0 2020-12-31  132.690002  0.114574  17001802.0

In [31]:
apple.dtypes

permno           float64
date      datetime64[ns]
prc              float64
ret              float64
shrout           float64
dtype: object

In [32]:
conn.describe_table(library='crsp', table='stocknames')

Approximately 63556 rows in crsp.stocknames.

         name  nullable              type
0      permno      True  DOUBLE_PRECISION
1      permco      True  DOUBLE_PRECISION
2      namedt      True              DATE
3   nameenddt      True              DATE
4       cusip      True           VARCHAR
5      ncusip      True           VARCHAR
6      ticker      True           VARCHAR
7      comnam      True           VARCHAR
8       hexcd      True  DOUBLE_PRECISION
9      exchcd      True  DOUBLE_PRECISION
10      siccd      True  DOUBLE_PRECISION
11      shrcd      True  DOUBLE_PRECISION
12     shrcls      True           VARCHAR
13    st_date      True              DATE
14   end_date      True              DATE
15    namedum      True  DOUBLE_PRECISION

In [36]:
conn.describe_table(library='audit', table='auditopin')

Approximately 338200 rows in audit.auditopin.

                      name  nullable              type
0             audit_op_key      True  DOUBLE_PRECISION
1       auditor_affil_fkey      True  DOUBLE_PRECISION
2        auditor_affilname      True       VARCHAR(92)
3             auditor_fkey      True  DOUBLE_PRECISION
4             auditor_name      True       VARCHAR(70)
..                     ...       ...               ...
220          closestqu_tso      True  DOUBLE_PRECISION
221     closestqu_tso_date      True              DATE
222  closestqu_tso_markcap      True  DOUBLE_PRECISION
223     eventdate_aud_fkey      True  DOUBLE_PRECISION
224     eventdate_aud_name      True       VARCHAR(70)

[225 rows x 3 columns]